### ISSUE TITLE
"Find Usages" is broken with plugin enabled

### ISSUE THREAD

**Issue by Mikk36** [insperedia/yiidea-support#20]
As soon as I enable the plugin, I can't find usages properly any more.

For example, a class that has 29 usages listed is unable to find any besides one reference inside the class itself.
![image](https://github.com/user-attachments/assets/b3d05724-bb4a-4ed9-bd86-b2663ead52c4)

Plugin disabled:
![image](https://github.com/user-attachments/assets/84adc5f4-5b38-426b-8637-bc880e14eb33)

**Comment by insperedia** [comment]
Please post your IDE version.

**Comment by Mikk36** [comment]
PhpStorm 2024.1.5

**Comment by insperedia** [comment]
Also please check if there is any exceptions in ide.

**Comment by Mikk36** [comment]
There are exceptions thrown on IDE startup, I've reported them from the button "Report to Yii Framework Support" button.
The same errors were thrown with the old Yii2Support plugin.

`com.intellij.diagnostic.PluginException: Failed to build index 'Yii2Support.ComponentsIndex' for file file:///home/mikk/coding/<my_project>/<my_project>src/frontend/config/main.php (id = 3863) (file type = PHP) [Plugin: com.insperedia.yiiFramework]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.util.indexing.diagnostic.BrokenIndexingDiagnostics$DefaultListener.onFileIndexMappingFailed(BrokenIndexingDiagnostics.kt:47)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1594)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$22(FileBasedIndexImpl.java:1460)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$freezeFileTypeTemporarilyWithProvidedValueIn$15(FileTypeManagerImpl.java:731)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:795)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:727)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1413)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1387)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.getApplierForFileIndexUpdate$lambda$4(IndexUpdateRunner.kt:256)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:851)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:883)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.RwLockHolder.tryRunReadAction(RwLockHolder.kt:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:492)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:220)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.getApplierForFileIndexUpdate(IndexUpdateRunner.kt:259)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.kt:184)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.access$indexOneFileOfJob(IndexUpdateRunner.kt:47)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$doIndexFiles$2$1$1$1$1.invoke(IndexUpdateRunner.kt:141)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$doIndexFiles$2$1$1$1$1.invoke(IndexUpdateRunner.kt:135)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:320)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:197)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:196)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$doIndexFiles$2$1$1.invokeSuspend(IndexUpdateRunner.kt:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.util.indexing.impl.MapReduceIndexMappingException: java.lang.ClassCastException: class com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to class com.jetbrains.php.lang.psi.elements.StringLiteralExpression (com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl and com.jetbrains.php.lang.psi.elements.StringLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3133ccc5)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:260)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:286)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:63)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:29)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1590)
	... 53 more
Caused by: java.lang.ClassCastException: class com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl cannot be cast to class com.jetbrains.php.lang.psi.elements.StringLiteralExpression (com.jetbrains.php.lang.psi.elements.impl.ConcatenationExpressionImpl and com.jetbrains.php.lang.psi.elements.StringLiteralExpression are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3133ccc5)
	at com.insperedia.yiiFramework.configurations.ComponentsIndex.lambda$getIndexer$0(ComponentsIndex.java:43)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:318)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:254)
	... 57 more
`

**Comment by insperedia** [comment]
Maybe it is possible to send me "config/main.php" (by email)? I need to reproduce the problem.

**Comment by insperedia** [comment]
Fixed in 1.0.14
